version: '3.3'
services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
            # Where our data will be persisted
    volumes:
      - warhammer-board:/adminer

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'WH'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'Aa123456'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3002:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - warhammer-board:/var/lib/mysql
    
  
# Names our volume
volumes:
  warhammer-board: